/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddPriceRouteImport } from './routes/add-price'
import { Route as GoodsIndexRouteImport } from './routes/goods.index'
import { Route as GoodsGoodIdRouteImport } from './routes/goods.$goodId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPriceRoute = AddPriceRouteImport.update({
  id: '/add-price',
  path: '/add-price',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodsIndexRoute = GoodsIndexRouteImport.update({
  id: '/goods/',
  path: '/goods/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodsGoodIdRoute = GoodsGoodIdRouteImport.update({
  id: '/goods/$goodId',
  path: '/goods/$goodId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-price': typeof AddPriceRoute
  '/goods/$goodId': typeof GoodsGoodIdRoute
  '/goods/': typeof GoodsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-price': typeof AddPriceRoute
  '/goods/$goodId': typeof GoodsGoodIdRoute
  '/goods': typeof GoodsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-price': typeof AddPriceRoute
  '/goods/$goodId': typeof GoodsGoodIdRoute
  '/goods/': typeof GoodsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-price' | '/goods/$goodId' | '/goods/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-price' | '/goods/$goodId' | '/goods'
  id: '__root__' | '/' | '/add-price' | '/goods/$goodId' | '/goods/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddPriceRoute: typeof AddPriceRoute
  GoodsGoodIdRoute: typeof GoodsGoodIdRoute
  GoodsIndexRoute: typeof GoodsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-price': {
      id: '/add-price'
      path: '/add-price'
      fullPath: '/add-price'
      preLoaderRoute: typeof AddPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goods/': {
      id: '/goods/'
      path: '/goods'
      fullPath: '/goods/'
      preLoaderRoute: typeof GoodsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goods/$goodId': {
      id: '/goods/$goodId'
      path: '/goods/$goodId'
      fullPath: '/goods/$goodId'
      preLoaderRoute: typeof GoodsGoodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddPriceRoute: AddPriceRoute,
  GoodsGoodIdRoute: GoodsGoodIdRoute,
  GoodsIndexRoute: GoodsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
