/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddPriceRouteImport } from './routes/add-price'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as GoodsIndexRouteImport } from './routes/goods.index'
import { Route as GoodsGoodIdRouteImport } from './routes/goods.$goodId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPriceRoute = AddPriceRouteImport.update({
  id: '/add-price',
  path: '/add-price',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodsIndexRoute = GoodsIndexRouteImport.update({
  id: '/goods/',
  path: '/goods/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodsGoodIdRoute = GoodsGoodIdRouteImport.update({
  id: '/goods/$goodId',
  path: '/goods/$goodId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-price': typeof AddPriceRoute
  '/auth': typeof AuthRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/goods/$goodId': typeof GoodsGoodIdRoute
  '/goods/': typeof GoodsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-price': typeof AddPriceRoute
  '/auth': typeof AuthRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/goods/$goodId': typeof GoodsGoodIdRoute
  '/goods': typeof GoodsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-price': typeof AddPriceRoute
  '/auth': typeof AuthRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/goods/$goodId': typeof GoodsGoodIdRoute
  '/goods/': typeof GoodsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-price'
    | '/auth'
    | '/notes'
    | '/settings'
    | '/goods/$goodId'
    | '/goods/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-price'
    | '/auth'
    | '/notes'
    | '/settings'
    | '/goods/$goodId'
    | '/goods'
  id:
    | '__root__'
    | '/'
    | '/add-price'
    | '/auth'
    | '/notes'
    | '/settings'
    | '/goods/$goodId'
    | '/goods/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddPriceRoute: typeof AddPriceRoute
  AuthRoute: typeof AuthRoute
  NotesRoute: typeof NotesRoute
  SettingsRoute: typeof SettingsRoute
  GoodsGoodIdRoute: typeof GoodsGoodIdRoute
  GoodsIndexRoute: typeof GoodsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-price': {
      id: '/add-price'
      path: '/add-price'
      fullPath: '/add-price'
      preLoaderRoute: typeof AddPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goods/': {
      id: '/goods/'
      path: '/goods'
      fullPath: '/goods/'
      preLoaderRoute: typeof GoodsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goods/$goodId': {
      id: '/goods/$goodId'
      path: '/goods/$goodId'
      fullPath: '/goods/$goodId'
      preLoaderRoute: typeof GoodsGoodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddPriceRoute: AddPriceRoute,
  AuthRoute: AuthRoute,
  NotesRoute: NotesRoute,
  SettingsRoute: SettingsRoute,
  GoodsGoodIdRoute: GoodsGoodIdRoute,
  GoodsIndexRoute: GoodsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
